# docker-compose.yml
version: '3.8'

services:
  tcp-proxy-bridge:
    build: .
    ports:
      - "8080:8080"  # 健康检查端口
      - "9999:9999"  # TCP服务端口
    environment:
      - CONFIG_FILE=/app/configs/config.yaml
    volumes:
      - ./configs:/app/configs  # 挂载配置文件目录
    depends_on:
      - postgres  # 依赖PostgreSQL服务
    healthcheck:
      # 健康检查：通过HTTP检查应用健康状态
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s    # 每30秒检查一次
      timeout: 10s     # 检查超时时间
      retries: 3       # 重试3次后标记为不健康
      start_period: 40s # 启动后40秒开始检查
    restart: unless-stopped  # 自动重启策略

  postgres:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=tcp_proxy    # 数据库名
      - POSTGRES_USER=user       # 数据库用户
      - POSTGRES_PASSWORD=pass   # 数据库密码
    volumes:
      - postgres_data:/var/lib/postgresql/data  # 数据持久化
      - ./scripts/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql  # 初始化脚本
    healthcheck:
      # 数据库健康检查
      test: ["CMD-SHELL", "pg_isready -U user -d tcp_proxy"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

volumes:
  postgres_data:  # PostgreSQL数据卷