# configs/config_active_mode.yaml
# 主动连接模式配置文件

server:
  tcp_listen_port: 9999        # TCP服务监听端口（暂时不使用）
  health_check_port: 8080      # 健康检查服务端口
  max_connections: 1000        # 最大并发连接数
  read_timeout: 30s            # 读取超时时间
  write_timeout: 30s           # 写入超时时间
  max_message_size: 65536      # 最大消息大小(64KB)

database:
  host: "postgres"             # 数据库主机
  port: 5432                   # 数据库端口
  user: "user"                 # 数据库用户
  password: "pass"             # 数据库密码
  name: "tcp_proxy"            # 数据库名
  max_open_conns: 50           # 最大打开连接数
  max_idle_conns: 25           # 最大空闲连接数
  conn_max_lifetime: "5m"      # 连接最大生命周期

forwarder:
  batch_size: 100              # 批量处理大小
  process_interval: "5s"       # 处理间隔
  max_processing_workers: 10   # 最大处理工作线程数
  base_retry_interval: "30s"   # 基础重试间隔
  max_retry_interval: "10m"    # 最大重试间隔

# 源服务器配置 - 主动连接模式
source_servers:
  primary:
    id: "primary-server"              # 主服务器唯一标识
    name: "主源服务器"                # 服务器显示名称
    address: "192.168.1.100:8888"     # 服务器地址
    enabled: true                     # 是否启用
    timeout: "10s"                    # 连接超时时间
    max_retries: 5                    # 最大重试次数
    batch_size: 100                   # 批量处理大小
    health_check_interval: "30s"      # 健康检查间隔
    health_check_timeout: "5s"        # 健康检查超时
    failover_threshold: 3             # 故障切换阈值（连续失败次数）
    
  backup:
    id: "backup-server"               # 备用服务器唯一标识
    name: "备用源服务器"              # 服务器显示名称
    address: "192.168.1.101:8888"     # 服务器地址
    enabled: true                     # 是否启用
    timeout: "10s"                    # 连接超时时间
    max_retries: 3                    # 最大重试次数
    batch_size: 50                    # 批量处理大小
    health_check_interval: "30s"      # 健康检查间隔
    health_check_timeout: "5s"        # 健康检查超时
    failover_threshold: 3             # 故障切换阈值（连续失败次数）

# 身份认证配置
authentication:
  token: "11111111111111111111111111111111"  # 32字节认证令牌
  source_id: 802                            # 信源ID (0x322 = 802)
  host_id: 20                               # 信宿ID (0x0014 = 20)
  reauth_interval: "1h"                     # 重新认证间隔

# 心跳配置
heartbeat:
  interval: "60s"                           # 心跳发送间隔
  write_idle_timeout: "3s"                  # 写空闲超时
  read_idle_timeout: "60s"                  # 读空闲超时

# 数据包分隔符配置
delimiter:
  separator: "7878787888888888"             # 分隔符 (十六进制字符串)
  max_packet_length: 4096                   # 最大数据包长度

# 目标服务器配置 - 转发目标
target_servers:
  - id: "target-1"                    # 服务器唯一标识
    name: "目标服务器1"               # 服务器显示名称
    address: "192.168.1.200:9999"     # 服务器地址
    enabled: true                     # 是否启用
    timeout: "10s"                    # 连接超时时间
    max_retries: 5                    # 最大重试次数
    batch_size: 100                   # 批量处理大小
    priority: 1                       # 优先级（数字越小优先级越高）

  - id: "target-2"
    name: "目标服务器2"
    address: "192.168.1.201:9999"
    enabled: true
    timeout: "10s"
    max_retries: 3
    batch_size: 50
    priority: 2

  - id: "target-3"
    name: "日志服务器"
    address: "192.168.1.202:9999"
    enabled: false                    # 暂时禁用
    timeout: "5s"
    max_retries: 2
    batch_size: 200
    priority: 3
